---
name: "Last.fm"
guid: "5e7fe7f0-b048-429e-a431-b1a7e69c930d"
version: "10.11.0.3"
targetAbi: "10.11.0.3"
framework: "net9.0"
overview: "A plugin that scrobbles your Jellyfin music to Last.fm"
description: >
  Scrobble Last.fm plays with Jellyfin.
category: "Music"
owner: "jesseward"
artifacts:
  - "Jellyfin.Plugin.Lastfm.dll"
changelog: >
  Fix naming consistency and Jellyfin dependencies.
